# Generated by Django 5.1.4 on 2025-01-05 19:03

import django.core.validators
import django.db.models.deletion
import shopping.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('current_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='shopping_it_name_aaa175_idx'), models.Index(fields=['-last_updated'], name='shopping_it_last_up_5c422c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('submitted', 'List Submitted'), ('processing', 'Admin Processing'), ('quoted', 'Quote Ready'), ('accepted', 'Quote Accepted'), ('declined', 'Quote Declined'), ('completed', 'Order Completed')], default='submitted', max_length=20)),
                ('customer_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')])),
                ('customer_phone', models.CharField(help_text='Enter a valid phone number', max_length=15, validators=[shopping.validators.validate_ug_phone])),
                ('delivery_address', models.TextField()),
                ('special_instructions', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='shopping_sh_created_2cbd7d_idx'), models.Index(fields=['status'], name='shopping_sh_status_68a225_idx'), models.Index(fields=['customer_email'], name='shopping_sh_custome_9cb027_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.CharField(help_text="Specify quantity (e.g., '2 kg', '3 pieces')", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shopping_items/%d/%m/%Y')),
                ('price_added', models.BooleanField(default=False)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=0, help_text='Price in UGX', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.shoppinglist')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=0, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('shopping_list', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='shopping.shoppinglist')),
            ],
        ),
    ]
