# Generated by Django 5.1.4 on 2025-01-15 09:30

import django.core.validators
import shopping.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='archived',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='customer_email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='customer_phone',
            field=models.CharField(max_length=15, validators=[shopping.validators.validate_ug_phone]),
        ),
    ]
