# Generated by Django 5.1.4 on 2025-01-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_shoppinglist_archived_shoppinglist_archived_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
