# Generated by Django 5.1.4 on 2025-01-15 11:24

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_shoppinglist_archived'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shoppinglist',
            managers=[
                ('active_lists', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='archived_at',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='archived',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='quote',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
