# Generated by Django 5.1.4 on 2025-01-15 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_alter_shoppinglist_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shoppinglist',
            managers=[
            ],
        ),
    ]
