# Generated by Django 5.1.4 on 2025-01-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_alter_shoppinglist_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
