# Generated by Django 5.1.4 on 2025-01-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AddField(
            model_name='payment',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the payment was successfully completed', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('pesapal', 'PesaPal')], default='pesapal', help_text='The payment service provider handling this transaction', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='status_description',
            field=models.TextField(blank=True, help_text='Detailed status information from payment provider', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='merchant_reference',
            field=models.CharField(help_text='Our unique reference for this payment', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_tracking_id',
            field=models.CharField(blank=True, help_text="PesaPal's order tracking ID for online payments", max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Money'), ('card', 'Credit/Debit Card')], help_text='The specific payment method used by the customer', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
